[package]
name = "rust_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = {workspace = true}
serde_derive = {workspace = true}
serde_json = {workspace = true}
walkdir = {workspace = true}
clap = {workspace = true}
indicatif = {workspace = true}
# tree sitter
# log
log = {workspace = true}
log4rs = {workspace = true}
lazy_static = {workspace = true}