[package]
name = "cve-dataset"
version = "0.1.0"
edition = "2021"
exclude = ["data/*"]

[features]
parrallelize = ["dep:rayon"] # add rayon to dependencies to parallelize

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
download_dataset = { path = "./crawler/download_dataset" }
clap = { version = "4.2.5", features = ["derive"] }
regex = "1.10.2"
walkdir = "2.4.0"
serde = "1.0.159"
serde_derive = "1.0.159"
serde_json = "1.0.115"

zip = "2.1.3"

rayon = {version = "1.9.0", optional = true}