[package]
name = "cve-dataset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
regex = "1.10.2"
walkdir = "2.4.0"
serde = "1.0.159"
serde_derive = "1.0.159"

tree-sitter = "0.20.9"
tree-sitter-rust = "0.20.4"
tree-sitter-c = "0.20.8"
tree-sitter-cpp = "0.20.5"
tree-sitter-php = "0.20.0"
tree-sitter-java = "0.20.2"
tree-sitter-query = "0.1.0"