[workspace]
resolver = "2"
members = [
    "rust_utils",
    "normalize_dataset",
    "download_dataset",
    "github_requester",
    "patch_fix"
]

[workspace.dependencies]

clap = { version = "4.2.5", features = ["derive"] }

serde = "1.0.159"
serde_derive = "1.0.159"
serde_json = "1.0.94"

walkdir = "2.4.0"

log = "0.4.20"
log4rs = "1.2.0"

dotenv = "0.15.0"

csv = "1.3.0"
regex = "1.10.4"
lazy_static = "1.4.0"
reqwest = { version = "0.12.2", features = ["blocking", "json"] }
indicatif = { version = "0.17.7", features = ["rayon"] } 

zip = "1.2.1"

postgres = "0.19.7"
sqlite = "0.36.0"