[package]
name = "github_requester"
version = "0.1.0"
edition = "2021"



[dependencies]
lazy_static = "1.4.0"
reqwest = { version = "0.12.2", features = ["blocking", "json"] }

log = "0.4.20"

serde = "1.0.159"
serde_derive = "1.0.159"
serde_json = "1.0.115"