[package]
name = "normalize_dataset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_utils = { path = "../rust_utils" }
dotenv = {workspace = true}
log = {workspace = true}
clap = {workspace = true}
csv = {workspace = true}
regex = {workspace = true}
lazy_static = {workspace = true}

serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }

sqlite = { workspace = true }
postgres = { workspace = true }