[package]
name = "download_dataset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_utils = { path = "../rust_utils" }
normalize_dataset = { path = "../normalize_dataset" }
github_requester = { path = "../github_requester" }
dotenv = {workspace = true}
log = {workspace = true}
clap = {workspace = true}
reqwest = {workspace = true}
walkdir = {workspace = true}
lazy_static = {workspace = true}
indicatif = {workspace = true}

serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
