[package]
name = "patch_fix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
download_dataset = { path = "../download_dataset" }
rust_utils = { path = "../rust_utils" }
dotenv = {workspace = true}
log = {workspace = true}
clap = {workspace = true}
walkdir = {workspace = true}
lazy_static = {workspace = true}
indicatif = {workspace = true}

serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }

zip = { workspace = true }
